### PR TITLE
using memcache::Connectable as constructor param

### PR DESCRIPTION
**Pull request by aisk**
Since memcache crate [exposed the `memcache::Connectable` in version 0.7.1](https://github.com/aisk/rust-memcache/pull/21), we can reuse it in this crate.

### CODE REVIEW

**Comment by megumish** [comment]
@aisk 
Sorry to delay the merge.
And I can not manage it anymore, so I will transfer ownership of this repository and crate if you like it.

**Comment by aisk** [comment]
@megumish Sorry to hear this, and it's ok if you want transfer this repo and crate to me. Thanks for the contributions for open source community!

**Comment by megumish** [comment]
@aisk Thank you. I have invited to be an owner of this crate.
And I tried to transfer this repo to you, but I can't because you have "r2d2-memcache" repo. 
So I have invited you to be a collaborator. Please check it.

**Comment by aisk** [comment]
Thanks @megumish , and can you add me as owner (or whatever staff with publish permission) on crates.io of this package? Here is my account: https://crates.io/users/aisk .

**Pull request merged**
