### PR TITLE
update memcache version

### PR DESCRIPTION
**Pull request by jcollonville**

### CODE REVIEW

**Comment by aisk** [comment]
I think it's better to upgrade the minor version (to "0.6.0").

And FYI, memcache crate have builtin connection pool, so you can use it without r2d2-memcache. You can create a connection pool with this method: https://docs.rs/memcache/0.15.0/memcache/struct.Client.html#method.with_pool_size . The default `connect` method using one connection as older versions' behavoir so using it with r2d2-memcache still works.

**Comment by jcollonville** [comment]
changed the version number.
Thanks for the memcache connection pool pointer, I first had to keep my projects compiling but will make the changes in the code.

**Comment by aisk** [comment]
Merged, and published on crates.io, thanks for contribution!

**Comment by jcollonville** [comment]
That was quick! thanks to you

**Pull request merged**
